### ISSUE TITLE
Unauthorized access depending on the QueryApi.query method used

### ISSUE THREAD

**Issue by alsacco38** [influxdata/influxdb-client-java#175]
__Steps to reproduce:__
Setup a connection with username and password and try to execute a query using `QueryApi.query(Query query, String org)` first and then try with  `QueryApi.query(Query query, String org, BiConsumer<Cancellable,FluxRecord> onNext, Consumer<? super Throwable> onError, Runnable onComplete)` .

I share the two methods that create the conncection and execute the query:

```java
protected InfluxDBClient getConnection() {
        DbProps props = config.getDbs().get(source);
        return InfluxDBClientFactory.create(props.getUrl(), props.getUser(), props.getPassword().toCharArray());
}

...

/* WORKING */
@Override
protected void executeQuery1(InfluxDBClient connection, QueryWrapper stmnt, Consumer<InfluxResult2> tc) 
        throws Exception {    
    QueryApi queryClient = connection.getQueryApi();
    String query= stmnt.getQueryString();
    System.out.println("Query: \n"+query);

    List<FluxTable> tables = queryClient.query(query, "isp");

    List<FluxRecord> records = tables.get(0).getRecords();
    for (FluxRecord fr : records) {
        onNext(fr, tc);
        Map<String, Object> jsonRes = fr.getValues();
        System.out.println(jsonRes);
    }
    onComplete(tc);
}

/* NOT WORKING */
@Override
protected void executeQuery2(InfluxDBClient connection, QueryWrapper stmnt, Consumer<InfluxResult2> tc) 
        throws Exception {
    QueryApi queryClient = connection.getQueryApi();
    String query = stmnt.getQueryString();
    System.out.println("Query: \n"+query);

    queryClient.query(query, "isp", (cancellable, fluxRecord) -> {
        onNext(fluxRecord, tc);
    }, (error) -> {
        System.out.println(error);
        onComplete(tc);
    }, new Runnable() {
        @Override
        public void run() {
            onComplete(tc);
        }
    });
}
```

__Expected behavior:__
In the second case _(executeQuery2)_, where the onNext, onError and onClomplete are implemented, it should return each record in `OnNext` and call the `onClompleted` at last, when all records have been handled.

__Actual behavior:__
With the first method _(executeQuery1)_, the execution returns the correct result, with the second one _(executeQuery2)_ instead, it throws the folloing exception: `com.influxdb.exceptions.UnauthorizedException: unauthorized access`.

__Specifications:__
**InfluxDB runs on docker, with the following docker-compose specs:**
```
influxdb2:
        image: quay.io/influxdb/influxdb:2.0.0-rc
        container_name: influxdb2
        ports:
            - "8087:8086"
        networks:
            - my_network
        volumes:
            - ./../import/influxdb2/:/tmp
            - ./infrastructure/database/influxdb2:/var/lib/influxdb
```

**pom dependency**:
```
<dependency>
	<groupId>com.influxdb</groupId>
	<artifactId>influxdb-client-java</artifactId>
	<version>1.13.0</version>
</dependency>
```

 **JDK Version:** 1.8
